#-----------------------------------------------------------------------------------------------------------------------
# Datasource
#-----------------------------------------------------------------------------------------------------------------------
datasource:
  microdms:
    db-type: postgresql
    host: postgres
    db-name: microdms
    username: mdsa
    password: mdsa
    max-pool-size: 30
    socket-timeout: 20000
